MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
  NUM_CLASSES: 10
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
  NUM_CLASSES: 10
DATASET_SOURCE:
  TYPE: "A2D2SCN"
  TRAIN: ("train",)
  A2D2SCN:
    preprocess_dir: "../../../4t/datasets/datasets_local/datasets_mjaritz/a2d2_preprocess"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "../../../4t/datasets/datasets_local/datasets_mjaritz/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "../../../4t/datasets/datasets_local/datasets_mjaritz/semantic_kitti_preprocess"
DATALOADER:
  NUM_WORKERS: 0
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
OPTIMIZER_D1:
  TYPE: "Adam"
  BASE_LR: 0.0001
  POWER: 0.9
OPTIMIZER_D2:
  TYPE: "Adam"
  BASE_LR: 0.0001
  POWER: 0.9
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.89090012, 2.0585112, 3.1970535, 3.1111633, 1., 2.93751704, 1.92053733,
                  1.47886874, 1.04654198, 1.78266561]
  XMUDA:
    lambda_xm_src: 0.05
    lambda_xm_trg: 0.001
    D_adv_src_2d: 0.1
    D_adv_src_3d: 0.1
    D_adv_trg_2d: 0.15
    D_adv_trg_3d: 0.15
    G_adv_trg_2d: 0.07
    G_adv_trg_3d: 0.07
VAL:
  BATCH_SIZE: 2
  PERIOD: 5000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/xmuda